replicaCount: 1

image:
  repository: us-central1-docker.pkg.dev/my-gcp-project/app-images/helloapp
  tag: main
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80
  targetPort: 8080

podAnnotations: {}

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "300m"
    memory: "256Mi"

env:
  name: "staging"   # overridden per environment

# Reference to an existing Kubernetes Secret that contains APP_MESSAGE
# The pipeline will create/update this secret from GCP Secret Manager.
existingSecret:
  name: "app-message"
  key: "APP_MESSAGE"
